### ISSUE TITLE
Generate Chapter is Borked

### ISSUE THREAD

**Issue by gisikw** [napcs/docbook#4]
Generate chapter creates the following:
- chapter/images/sample.png
- chapter/w3centities-f.end
- chapter.xml

It should generate:
- chapter/images/sample.png
- chapter/w3centities-f.end
- chapter/chapter.xml

**Comment by napcs** [comment]
This is expected behavior

generate chapter mychapter  generates   a mychapter folder and a mychapter.xml file

generate chapter mychapter/mychapter generates what you're looking for, 

This is by design, though it may not be documented ideally. If you think an alternate option is necessary, fork and send a pull request.
